### ISSUE TITLE
[BUG] CLI always exits with code 1 on success

### ISSUE THREAD

**Issue by joernweissenborn** [guerinoni/qt-ts-csv#63]
**Describe the bug**
Even when successful, qTsConverter returns with `1` after conversion. Continuous integration don't like this.

**To Reproduce**
1. Do conversion in CLI mode
1. look at exit code.

**Expected behavior**
On successful conversion exit code `0` should be returned.

**Additional context**
As mentioned, this is crucial for CI/CD integration.

**Comment by guerinoni** [comment]
I think last commit can fix this :)
Thanks for issue
